DROP TABLE IF EXISTS login_logs;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS user_clients;
DROP TABLE IF EXISTS wallet_nonces;
DROP TABLE IF EXISTS user_wallets;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS users;
